// 6 条冥想（来自 SelfCEO src/lib/meditations-data.ts）
export const meditationsData = [
  {
    title: '晨间正念',
    description: '开启美好一天的 5 分钟正念练习',
    category: 'focus' as const,
    durationMin: 5,
    tags: [{ tag: 'morning' }, { tag: 'focus' }],
    script: [
      { step: '坐下来，让肩膀松下来' },
      { step: '深吸一口气，慢慢呼出' },
      { step: '感受空气从鼻尖进入身体' },
      { step: '让每一次呼吸都带走一点紧绷' },
      { step: '感受当下这一刻的平静' },
    ],
    isPublished: true,
    sortOrder: 1,
  },
  {
    title: '呼吸减压',
    description: '4-7-8 呼吸法，快速缓解焦虑',
    category: 'stress' as const,
    durationMin: 7,
    tags: [{ tag: 'breathing' }, { tag: 'anxiety' }],
    script: [
      { step: '找一个安静的地方坐下' },
      { step: '用鼻子吸气，默数 4 拍' },
      { step: '屏住呼吸，默数 7 拍' },
      { step: '用嘴呼出，默数 8 拍' },
      { step: '重复 4 次' },
    ],
    isPublished: true,
    sortOrder: 2,
  },
  {
    title: '助眠冥想',
    description: '引导你进入深度睡眠的身体扫描',
    category: 'sleep' as const,
    durationMin: 15,
    tags: [{ tag: 'sleep' }, { tag: 'relaxation' }],
    script: [
      { step: '躺下来，闭上眼睛' },
      { step: '深吸一口气，感受身体的重量' },
      { step: '从脚趾开始，逐渐放松' },
      { step: '将注意力移到小腿，感受温暖' },
      { step: '继续向上，放松膝盖、大腿' },
      { step: '感受腹部随着呼吸起伏' },
    ],
    isPublished: true,
    sortOrder: 3,
  },
  {
    title: '专注力训练',
    description: '番茄钟配合的正念集中练习',
    category: 'focus' as const,
    durationMin: 10,
    tags: [{ tag: 'focus' }, { tag: 'productivity' }],
    script: [
      { step: '坐直，双脚踩地' },
      { step: '设定一个专注目标' },
      { step: '深吸一口气，清空杂念' },
      { step: '将注意力带回到当下任务' },
      { step: '当思绪飘走时，温柔地拉回来' },
    ],
    isPublished: true,
    sortOrder: 4,
  },
  {
    title: '情绪释放',
    description: '温柔地处理困难情绪的冥想',
    category: 'stress' as const,
    durationMin: 12,
    tags: [{ tag: 'emotion' }, { tag: 'release' }],
    script: [
      { step: '闭上眼睛，注意当下的感受' },
      { step: '给这个情绪起一个名字' },
      { step: '不评判，只是观察' },
      { step: '想象情绪是一朵云，慢慢飘过' },
      { step: '深呼吸，让自己回到中心' },
    ],
    isPublished: true,
    sortOrder: 5,
  },
  {
    title: '感恩日记',
    description: '睡前三件好事，培养积极心态',
    category: 'sleep' as const,
    durationMin: 8,
    tags: [{ tag: 'gratitude' }, { tag: 'evening' }],
    script: [
      { step: '静下来，回顾今天' },
      { step: '想到第一件让你感到感激的小事' },
      { step: '在心里默默感谢它' },
      { step: '再想到第二件' },
      { step: '再想到第三件' },
      { step: '带着这份温暖入睡' },
    ],
    isPublished: true,
    sortOrder: 6,
  },
]

// 5 门课程（来自 SelfCEO src/lib/courses-data.ts）
export const coursesData = [
  {
    title: '10天正念基础',
    description: '从零开始建立正念习惯，每天 10 分钟，改变从现在开始',
    category: 'mindfulness' as const,
    durationDays: 10,
    isPremium: false,
    isPublished: true,
    sortOrder: 1,
  },
  {
    title: '3周焦虑缓解（认知行为疗法）',
    description: '基于 CBT 原理，系统识别和改变焦虑思维模式',
    category: 'CBT' as const,
    durationDays: 21,
    isPremium: false,
    isPublished: true,
    sortOrder: 2,
  },
  {
    title: '4周情绪韧性（接受承诺疗法）',
    description: '学习与困难情绪共处，而非逃避，建立心理灵活性',
    category: 'ACT' as const,
    durationDays: 28,
    isPremium: true,
    isPublished: true,
    sortOrder: 3,
  },
  {
    title: '3周改善睡眠（失眠CBT-I）',
    description: '科学有效的失眠认知行为疗法，重建睡眠节律',
    category: 'CBT-I' as const,
    durationDays: 21,
    isPremium: true,
    isPublished: true,
    sortOrder: 4,
  },
  {
    title: '2周自我同情（正念认知疗法）',
    description: '学会温柔对待自己，从自我批评转向自我关怀',
    category: 'MBCT' as const,
    durationDays: 14,
    isPremium: false,
    isPublished: true,
    sortOrder: 5,
  },
]

// 8 条碎片微练习（来自 SelfCEO src/lib/fragments-data.ts）
export const fragmentsData = [
  {
    title: '一次完整的深呼吸',
    durationMin: '1' as const,
    category: 'breath' as const,
    hook: '只要 60 秒，让神经先慢下来',
    steps: [
      { step: '坐稳，肩膀放下来' },
      { step: '用鼻子慢慢吸气，数 4 拍' },
      { step: '屏住，数 4 拍' },
      { step: '用嘴慢慢呼出，数 6 拍' },
      { step: '再来两次' },
    ],
    isPublished: true,
  },
  {
    title: '5-4-3-2-1 五感着陆',
    durationMin: '2' as const,
    category: 'sense' as const,
    hook: '把注意力拉回身体，停止反刍',
    steps: [
      { step: '看：说出你看到的 5 件东西' },
      { step: '摸：感受 4 种不同的触感' },
      { step: '听：注意 3 种声音' },
      { step: '闻：找到 2 种气味' },
      { step: '尝：感受嘴里 1 种味道' },
    ],
    isPublished: true,
  },
  {
    title: '让身体松一档',
    durationMin: '2' as const,
    category: 'body' as const,
    hook: '两分钟全身释放，比咖啡更提神',
    steps: [
      { step: '站起来，抖动双手' },
      { step: '转动脖子，顺时针三圈' },
      { step: '耸肩到耳朵，停三秒，放下' },
      { step: '深吸气时挺胸，呼气时松垮' },
      { step: '重复三次' },
    ],
    isPublished: true,
  },
  {
    title: '给情绪起个名字',
    durationMin: '3' as const,
    category: 'mind' as const,
    hook: '命名情绪，减少其对你的控制',
    steps: [
      { step: '暂停手里的事' },
      { step: '问自己：我现在感觉怎么样？' },
      { step: '不评判，只是观察' },
      { step: '给它起一个具体的名字（焦虑/委屈/烦躁）' },
      { step: '对自己说：我现在感到__，这没关系' },
    ],
    isPublished: true,
  },
  {
    title: '一句自我同情语',
    durationMin: '3' as const,
    category: 'mind' as const,
    hook: '用对待好友的方式对待自己',
    steps: [
      { step: '想象你最好的朋友正在经历你的处境' },
      { step: '你会对他说什么？' },
      { step: '现在，把这句话对自己说' },
      { step: '把手放在心口，感受这句话' },
      { step: '深呼吸，接受这份关怀' },
    ],
    isPublished: true,
  },
  {
    title: '一杯水的正念',
    durationMin: '3' as const,
    category: 'sense' as const,
    hook: '用一杯水练习完全在场',
    steps: [
      { step: '倒一杯水，感受杯子的重量和温度' },
      { step: '观察水的颜色和透明度' },
      { step: '慢慢喝一口，感受水在嘴里的感觉' },
      { step: '感受水流进喉咙、身体' },
      { step: '感谢这一刻的存在' },
    ],
    isPublished: true,
  },
  {
    title: '快速身体扫描',
    durationMin: '5' as const,
    category: 'body' as const,
    hook: '5 分钟，从头到脚重新认识自己的身体',
    steps: [
      { step: '闭上眼睛，深呼吸三次' },
      { step: '注意头部：有紧绷感吗？' },
      { step: '移到颈肩：感受并放松' },
      { step: '胸口和腹部：随呼吸起伏' },
      { step: '双手和双脚：感受末梢' },
      { step: '整体感受：此刻的身体状态' },
    ],
    isPublished: true,
  },
  {
    title: '三件小事',
    durationMin: '5' as const,
    category: 'mind' as const,
    hook: '用感恩重新调校今天的频率',
    steps: [
      { step: '停下来，深呼吸' },
      { step: '回想今天一件让你感到轻松的小事' },
      { step: '停留在那个感觉里 10 秒' },
      { step: '再想一件有趣或暖心的小事' },
      { step: '最后一件：任何你感激的事' },
    ],
    isPublished: true,
  },
]

// 12 个关系教练场景（来自 SelfCEO src/lib/relationship-data.ts）
export const scenariosData = [
  // 伴侣
  {
    title: 'TA 最近变得冷淡',
    description: '感觉关系出现了距离',
    group: 'partner' as const,
    prompt: '我和伴侣最近关系有些疏远，TA 变得比较冷淡，不太主动联系我，我不知道是不是我做错了什么，还是TA自己有压力。我想了解如何温柔地开启一次对话，而不是让对方感到被审问。',
    isPublished: true,
    sortOrder: 1,
  },
  {
    title: '我们刚吵了一架',
    description: '争吵后如何修复',
    group: 'partner' as const,
    prompt: '我和伴侣刚刚吵了一架，现在都很生气，气氛很僵。我不确定是该先道歉还是等TA冷静。我想找到一种方式在不委屈自己的情况下，修复这段关系。',
    isPublished: true,
    sortOrder: 2,
  },
  {
    title: '讨论未来的不确定',
    description: '对未来规划有分歧',
    group: 'partner' as const,
    prompt: '我和伴侣对未来的规划有些分歧，比如在哪里生活、要不要孩子等问题。我担心如果深聊会引发争吵，但又觉得不能一直回避。想学习如何进行这种重要而不伤感情的对话。',
    isPublished: true,
    sortOrder: 3,
  },
  // 父母
  {
    title: '父母总是干涉我的选择',
    description: '边界感的建立',
    group: 'parents' as const,
    prompt: '我的父母经常对我的工作、感情、生活方式表达强烈意见，让我感到窒息。我已经是成年人了，但每次试图表达边界都会引发家庭冲突。想找到既能维护自己、又不伤害家人感情的方式。',
    isPublished: true,
    sortOrder: 4,
  },
  {
    title: '父母在慢慢老去',
    description: '面对父母的衰老与需求',
    group: 'parents' as const,
    prompt: '我注意到父母身体越来越差，开始需要更多照顾，但我也有自己的生活和工作压力。我感到内疚、无力，不知道如何在照顾父母和维持自己生活之间找到平衡。',
    isPublished: true,
    sortOrder: 5,
  },
  {
    title: '达不到父母的期待',
    description: '与父母期望的落差',
    group: 'parents' as const,
    prompt: '我感觉自己一直在让父母失望，无论是学业、工作还是婚姻。我知道他们是为我好，但这种期待压力让我喘不过气，有时甚至不想与他们沟通。想学习如何处理这种关系中的情绪。',
    isPublished: true,
    sortOrder: 6,
  },
  // 同事
  {
    title: '领导一直给我加活',
    description: '工作边界与过载',
    group: 'colleague' as const,
    prompt: '我的领导经常在下班前或周末给我安排额外任务，我不好意思拒绝，但已经感到严重超载。想学习如何在不影响职场关系的情况下，温和而坚定地设立工作边界。',
    isPublished: true,
    sortOrder: 7,
  },
  {
    title: '同事把锅推给我',
    description: '职场中的责任归因',
    group: 'colleague' as const,
    prompt: '项目出了问题，同事在领导面前暗示是我的责任，但实际上不是。我既生气又不知道如何回应，担心直接对抗会影响团队关系。想找到既能澄清事实又不激化矛盾的方式。',
    isPublished: true,
    sortOrder: 8,
  },
  {
    title: '同事不配合我的工作',
    description: '跨部门协作的困难',
    group: 'colleague' as const,
    prompt: '我需要某个同事的配合才能推进工作，但TA经常不回复消息、拖延提供资料。我不确定是故意的还是只是太忙，想找到一种推进合作而不显得强硬的方式。',
    isPublished: true,
    sortOrder: 9,
  },
  // 朋友
  {
    title: '和好友渐渐疏远了',
    description: '友情的变淡与维系',
    group: 'friend' as const,
    prompt: '我和一个曾经很亲密的朋友最近越来越少联系，感觉关系在慢慢淡去。我不确定是否值得主动挽救，也不知道怎么重新建立联系而不显得刻意。',
    isPublished: true,
    sortOrder: 10,
  },
  {
    title: '朋友总向我倾诉，让我很累',
    description: '情感边界与支持',
    group: 'friend' as const,
    prompt: '我有个朋友经常向我倾诉负面情绪和问题，但从不问我的感受。我开始感到情感耗竭，但又不想伤害这段友情。想找到如何在关心朋友的同时，也保护自己的情感空间。',
    isPublished: true,
    sortOrder: 11,
  },
  {
    title: '感到孤独，不知如何建立真诚的连接',
    description: '深层孤独感',
    group: 'friend' as const,
    prompt: '我有很多认识的人，但很少有能真正深聊的朋友。我感到一种底层的孤独感，不确定是自己的问题还是现代生活方式导致的。想了解如何建立更有深度的人际连接。',
    isPublished: true,
    sortOrder: 12,
  },
]
